image: python:3.9

variables:
  QUARTO_VERSION: 1.1.189

pages:
  script:
    - wget "https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/quarto-${QUARTO_VERSION}-linux-amd64.deb"
    - dpkg -i quarto-${QUARTO_VERSION}-linux-amd64.deb
    - pip install jupyter
    - quarto check install
    - quarto check jupyter
    - pip install -r requirements.txt
    - rm -rf _site
    - quarto render
    - mv _site public
  artifacts:
    paths:
      - public
  only:
    - main

