project:
  type: website

website:
  title: "Atelier Données"
  site-url: https://gt-atelier-donnees.miti.cnrs.fr
  favicon: images/favicon.png
  page-navigation: true
  page-footer: 
    right: "Ce site a été créé avec [Quarto](https://quarto.org/)"
    left: "&copy; Ce(tte) œuvre est mise à disposition selon les termes de la [Licence Creative Commons Attribution 4.0 International](http://creativecommons.org/licenses/by/4.0/)."

  navbar:
    logo: images/petit-logo-simple-blanc.png
    href: https://mi-gt-donnees.pages.math.unistra.fr/quarto
    right:
    - text: "Actualités"
      href: actualite.qmd
    - text: "Guide de bonnes pratiques"
      href: guide.qmd
    - text: "Thématiques"
      menu:
        - href: datapaper.qmd
          text: "Datapaper"
        - href: fair.qmd
          text: "FAIRisation des données"
        - href: qualite.qmd
          text: "Qualité des données"
        - href: wikidata.qmd
          text: "Wikidata"
    - text: "Lettres d'Information"
      href: lettres.qmd
    - text: "Documents"
      href: docs.qmd
    - text: "FAQ"
      href: faq.qmd
    - text: Liste de discussion
      href: liste.qmd
    - text: "Membres"
      href: membres.qmd
    - icon: envelope-fill
      href: mailto:gt-donnees-inter-reseaux@groupes.renater.fr
      aria-label: "Contact"
    - icon: twitter
      href: https://twitter.com/miti_gt_donnees
    - icon: github
      href: https://github.com/miti-gt-donnees

format:
  html:
    lang: fr
    theme: cosmo
    css: styles.css
    toc: true
    toc-title: " "
    toc-location: body

