project:
  type: website

website:
  title: "Atelier Données"
  site-url: https://mi-gt-donnees.pages.math.unistra.fr/quarto
  
  page-footer: 
    right: "Ce site a été créé avec [Quarto](https://quarto.org/)"
    left: "&copy; Ce(tte) œuvre est mise à disposition selon les termes de la [Licence Creative Commons Attribution 4.0 International](http://creativecommons.org/licenses/by/4.0/)."
 
  navbar:
    href: https://gt-atelier-donnees.miti.cnrs.fr
    right:
    - text: "Lettres"
      href: lettres.qmd
    - text: "Evènements"
      href: evenements.qmd
    - text: "FAQ Données"
      href: faq.qmd
    - text: "Documents"
      href: docs.qmd
    - text: "Thématiques"
      menu:
        - href: fair.qmd
          text: "FAIR"
        - href: datapaper.qmd
          text: "Datapaper"
        - href: wikidata.qmd
          text: "Wikidata"
        - href: qualite.qmd
          text: "Qualité des données"
    - text: "Contact"
      href: contact.qmd
    - icon: github
      href: https://github.com/miti-gt-donnees
    - icon: twitter
      href: https://twitter.com/miti_gt_donnees

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-title: " "
    toc-location: body

