project:
  type: website

website:
  title: "Atelier Données"
  site-url: https://mi-gt-donnees.pages.math.unistra.fr/quarto
  
  page-footer: 
    right: "Ce site a été créé avec [Quarto](https://quarto.org/)"
    left: "&copy; Ce(tte) œuvre est mise à disposition selon les termes de la [Licence Creative Commons Attribution 4.0 International](http://creativecommons.org/licenses/by/4.0/)."
 
  navbar:
    logo: images/gt-donnees-logo.png
    href: https://gt-atelier-donnees.miti.cnrs.fr
    right:
    - text: "Datapaper"
      href: datapaper.qmd
    - text: "FAQ"
      href: faq.qmd
    - text: "FAIR"
      href: fair.qmd
    - text: "Documentation"
      href: documentation.qmd
    - text: "Evènements"
      href: evenements.qmd
    - text: "Contact"
      href: contact.qmd
    - text: "Wébinaire qualité"
      href: qualite.qmd
    - text: "Wébinaire wikidata"
      href: wikidata.qmd
    - icon: github
      href: https://github.com/miti-gt-donnees
    - icon: twitter
      href: https://twitter.com/miti_gt_donnees

format:
  html:
    theme: [sandstone, custom.scss]
    css: styles.css
    toc: true
    toc-title: " "
    toc-location: body

