project:
  type: website

website:
  title: "Atelier Données"
  site-url: https://nasa-openscapes.github.io/
  favicon: images/openscapes_hex.png  
  
  page-footer: 
    right: "Ce site a été créé avec [Quarto](https://quarto.org/)"
    left: "&copy; CC-By Atelier données"
 
  navbar:
    logo: images/gt-donnees-logo.png
    href: https://gt-atelier-donnees.miti.cnrs.fr
    right:
    - text: "Datapaper"
      href: datapaper.qmd
    - text: "FAQ"
      href: faq.qmd
    - text: "FAIR"
      href: fair.qmd
    - text: "Documentation"
      href: documentation.qmd
    - text: "Evènements"
      href: evenements.qmd
    - text: "Contact"
      href: contact.qmd
    - icon: github
      href: https://github.com/miti-gt-donnees
    - icon: twitter
      href: https://twitter.com/miti_gt_donnees

format:
  html:
    theme: [sandstone, custom.scss]
    css: styles.css
    toc: true
    toc-title: " "
    toc-location: body

