project:
  type: website

website:
  title: "Atelier Données"
  site-url: https://mi-gt-donnees.pages.math.unistra.fr/quarto
  favicon: images/favicon.png
  page-footer: 
    right: "Ce site a été créé avec [Quarto](https://quarto.org/)"
    left: "&copy; Ce(tte) œuvre est mise à disposition selon les termes de la [Licence Creative Commons Attribution 4.0 International](http://creativecommons.org/licenses/by/4.0/)."

  navbar:
    logo: "images/petit-logo.png"
    href: https://mi-gt-donnees.pages.math.unistra.fr/quarto
    right:
    - text: "Lettres"
      href: lettres.qmd
    - text: "FAQ"
      href: faq.qmd
    - text: "Documents"
      href: docs.qmd
    - text: "Thématiques"
      menu:
        - href: fair.qmd
          text: "FAIR"
        - href: datapaper.qmd
          text: "Datapaper"
        - href: wikidata.qmd
          text: "Wikidata"
        - href: qualite.qmd
          text: "Qualité des données"
    - text: "Membres"
      href: membres.qmd
    - icon: envelope-fill
      href: mailto:gt-donnees-inter-reseaux@groupes.renater.fr
    - icon: twitter
      href: https://twitter.com/miti_gt_donnees
    - icon: images/mailing.png
      href: https://listes.services.cnrs.fr/wws/info/donnees-inter-reseaux
    - icon: github
      href: https://github.com/miti-gt-donnees

format:
  html:
    lang: fr
    theme: cosmo
    css: styles.css
    toc: true
    toc-title: " "
    toc-location: body

