project:
  type: website

website:
  title: "Atelier Données"
  site-url: https://nasa-openscapes.github.io/
  favicon: images/openscapes_hex.png  
  
  page-footer: 
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/), with theme from [vetiver](https://github.com/rstudio/vetiver.rstudio.com)"
    left: "&copy; CC-By NASA Openscapes"
 
  navbar:
    logo: images/openscapes_hex.png
    href: https://gt-atelier-donnees.miti.cnrs.fr
    right:
    # - text: "Home"
    #   href: index.html
    - text: "About"
      href: about.qmd
    - text: "Contact"
      href: contact.qmd
    - text: "Datapaper"
      href: datapaper.qmd
    - text: "FAQ"
      href: faq.qmd
    - text: "FAIR"
      href: fair.qmd
    - text: "Documentation"
      href: documentation.qmd
    - text: "Evènements"
      href: events.qmd
    - icon: github
      href: https://github.com/miti-gt-donnees
    - icon: twitter
      href: https://twitter.com/miti_gt_donnees

format:
  html:
    theme: [sandstone, custom.scss]
    css: styles.css
    toc: true
    toc-title: Contents
    toc-location: left

