---
title: "Les Documents"
tags: [documents]
format:
  html:
    toc: false
---

- Les [archives](https://listes.services.cnrs.fr/wws/arc/donnees-inter-reseaux/) de la liste de discussion « donnees-inter-reseaux »
- Le [choix d'un entrepôt](/download/Choix_entrepot_hackathon_20200114.pdf) par Françoise Tisserand, Ourida Aberkane et Mohamed Yahi
- Le [poster](/download/R2T2-septembre-2019.pdf) pour les R2T2 : Rencontres des Réseaux Transverses et inTerdisciplinaires, 18-19 September 2019, CNRS Campus Gérard Mégie
- La [cartographie](/download/GTInterreseaux-CartoSyntheseV6-optimise.pdf) des usages dans chaque réseau autour de la gestion de la donnée
- Le [livret](/download/Livret_FAIR_2018.pdf) de la journée « Interopérabilité et pérennisation des données de la recherche : comment FAIR En pratique ? Retours d'expériences »
- [Présentation du GT Atelier Données](/download/Atelier_Donnees_17052021.pdf) lors de la réunion des coordinateurs des réseaux MITI (17/05/2021)
- [Présentation du GT Atelier Données](/download/Atelier_Donnees_20220420.pdf) lors de la réunion des coordinateurs des réseaux MITI (20/04/2022)
- [Le guide de bonnes pratiques sur la gestion des données de la recherche](https://mi-gt-donnees.pages.math.unistra.fr/guide/)
- Le webinaire de présentation du guide (Janvier 2021) ([video](https://www.canal-u.tv/video/atelier_donnees/presentation_du_guide_de_bonnes_pratiques_des_donnees_de_la_recherche.59537), [pdf](/download/Guide_Bonnes_Pratiques_Janvier_2021.pdf))

## Lettres d\'information de l'Atelier Données

- [n°1 - Juin 2020](/lettres/01-Juin_2020.md)
- [n°2 - Juillet 2020](/lettres/02-Juillet_2020.md)
- [n°3 - Septembre 2020](/lettres/03-Septembre_2020.md)
- [n°4 - Octobre 2020](/lettres/04-Octobre_2020.md)
- [n°5 - Novembre 2020](/lettres/05-Novembre_2020.md)
- [n°6 - Décembre 2020](/lettres/06-Décembre_2020.md)
- [n°7 - Janvier 2021](/lettres/07–Janvier_2021.md)
- [n°8 - Février 2021](/lettres/08–Février_2021.md)
- [n°9 - Mars 2021](/lettres/09-Mars_2021.md)
- [n°10 - Avril 2021](/lettres/10-Avril_2021.md)
- [n°11 - Mai 2021](/lettres/11-Mai_2021.md)
- [n°12 - Juin 2021](/lettres/12-Juin_2021.md)
- [n°13 - Juillet 2021](/lettres/13-Juillet_2021.md)
- [n°14 - Aout 2021](/lettres/14-Aout_2021.md)
- [n°15 - Septembre 2021](/lettres/15-Septembre_2021.md)
- [n°16 - Octobre_2021](/lettres/16-Octobre_2021.md) 
- [n°17 - Novembre_2021](/lettres/17-Novembre_2021.md)
- [n°18 - Décembre_2021](/lettres/18-Decembre_2021.md) 
- [n°19 - Janvier_2022](/lettres/19-Janvier_2022.md)
- [n°20 - Février_2022](/lettres/20-Février_2022.md) 
- [n°21 - Mars_2022](/lettres/21-Mars_2022.md)
- [n°22 - Avril_2022](/lettres/22-Avril_2022.md) 
- [n°23 - Mai_2022](/lettres/23-Mai_2022.md)
- [n°24 - Juin_2022](/lettres/24-Juin_2022.md)
- [n°25 - Juillet_2022](/lettres/25-Juillet_2022.md)
- [n°26 - Aout_2022](/lettres/26-Aout_2022.md)

