---
title: "Les Documents"
tags: [documents]
---

* Les [archives](https://listes.services.cnrs.fr/wws/arc/donnees-inter-reseaux/) de la liste de discussion « donnees-inter-reseaux »
* Le [choix d'un entrepôt](/download/Choix_entrepot_hackathon_20200114.pdf/) par Françoise Tisserand, Ourida Aberkane et Mohamed Yahi
* Le [poster](/download/R2T2-septembre-2019.pdf) pour les R2T2 : Rencontres des Réseaux Transverses et inTerdisciplinaires, 18-19 September 2019, CNRS Campus Gérard Mégie
* La [cartographie](/download/GTInterreseaux-CartoSyntheseV6-optimise.pdf) des usages dans chaque réseau autour de la gestion de la donnée
* Le [livret](/download/Livret_FAIR_2018.pdf) de la journée « Interopérabilité et pérennisation des données de la recherche : comment FAIR En pratique ? Retours d'expériences »
* [Présentation du GT Atelier Données](/download/Atelier_Donnees_17052021.pdf) lors de la réunion des coordinateurs des réseaux MITI (17/05/2021)
* [Présentation du GT Atelier Données](/download/Atelier_Donnees_20220420.pdf) lors de la réunion des coordinateurs des réseaux MITI (20/04/2022)


- [Le guide de bonnes pratiques sur la gestion des données de la recherche](https://mi-gt-donnees.pages.math.unistra.fr/guide/)
- Le webinaire de présentation du guide (Janvier 2021) ([video](https://www.canal-u.tv/video/atelier_donnees/presentation_du_guide_de_bonnes_pratiques_des_donnees_de_la_recherche.59537), [pdf](/download/Guide_Bonnes_Pratiques_Janvier_2021.pdf))

## Lettres d\'information de l'Atelier Données

- [n°1 - Juin 2020](/download/Lettre_d_information_GT_Atelier_Données_n_1_-_Juin_2020.pdf)
- [n°2 - Juillet 2020](/download/Lettre_d_information_GT_Atelier_Données_n_2_-_Juillet_2020.pdf)
- [n°3 - Septembre 2020](/download/Lettre_d_information_GT_Atelier_Données_n_3_-_Septembre_2020.pdf)
- [n°4 - Octobre 2020](/download/Lettre_d_information_GT_Atelier_Données_n_4_-_Octobre_2020.pdf)
- [n°5 - Novembre 2020](/download/Lettre_d_information_GT_Atelier_Données_n_5_-_Novembre_2020.pdf)
- [n°6 - Décembre 2020](/download/Lettre_d_information_GT_Atelier_Données_n_6_-_Décembre_2020.pdf)
- [n°7 - Janvier 2021](/download/Lettre_d_information_GT_Atelier_Données_n_7_–_Janvier_2021.pdf)
- [n°8 - Février 2021](/download/Lettre_d_information_GT_Atelier_Données_n_8_–_Février_2021.pdf)
- [n°9 - Mars 2021](/download/Lettre_d_information_GT_Atelier_Données_n_9___Mars_2021.pdf)
- [n°10 - Avril 2021](/download/Lettre_d_information_GT_Atelier_Données_n_10_-_Avril_2021.pdf)
- [n°11 - Mai 2021](/download/Lettre_d_information_GT_Atelier_Données_n_11_-_Mai_2021.pdf)
- [n°12 - Juin 2021](/download/Lettre_d_information_GT_Atelier_Données_n_12_-_Juin_2021.pdf)
- [n°13 - Juillet 2021](/download/Lettre_d_information_GT_Atelier_Données_n_13_-_Juillet_2021.pdf)
- [n°14 - Aout 2021](/download/Lettre_d_information_GT_Atelier_Données_n_14_-_Aout_2021.pdf)
- [n°15 - Septembre 2021](/download/Lettre_d_information_GT_Atelier_Données_n_15_-_Septembre_2021.pdf)
- [n°16 - Octobre_2021](/download/Lettre_d_information_GT_Atelier_Données_n_16_-_Octobre_2021.pdf) 
- [n°17 - Novembre_2021](/download/Lettre_d_information_GT_Atelier_Données_n_17_-_Novembre_2021.pdf)
- [n°18 - Décembre_2021](/download/Lettre_d_information_GT_Atelier_Données_n_18_Decembre_2021.pdf) 
- [n°19 - Janvier_2022](/download/Lettre_d_information_GT_Atelier_Données_n_19_Janvier_2022.pdf)
- [n°20 - Février_2022](/download/Lettre_d_information_GT_Atelier_Données_n_20_-_Février_2022.pdf) 
- [n°21 - Mars_2022](/download/Lettre_d_information_GT_Atelier_Données_n_21_-_Mars_2022.pdf)
- [n°22 - Avril_2022](/download/Lettre_d_information_GT_Atelier_Données_n_22_-_Avril_2022.pdf) 
- [n°23 - Mai_2022](/download/Lettre_d_information_GT_Atelier_Données_n_23_-_Mai_2022.pdf)
- [n°24 - Juin_2022](/download/Lettre_d_information_GT_Atelier_Données_n_24_-_Juin_2022.pdf)

