---
title: "Evènements"
subtitle: Actions organisées par le groupe
---

En 2017, le groupe a proposé un
[document](GTInterreseaux-CartoSyntheseV6-optimise.pdf)
qui cartographie les usages dans chaque réseau autour de la gestion
de la donnée.

En 2018, le groupe a organisé une journée thématique inter-réseaux
« Interopérabilité et pérennisation des données de la recherche :
Comment FAIR en pratique ? » :
[pdf](https://gt-donnees2018.sciencesconf.org/),
[visio](https://webcast.in2p3.fr/container/interoperabilite-et-perennisation-des-donnees-de-la-recherche).

En 2019, le groupe a participé aux journées R2T2 « Atelier données : un gt inter-réseaux pour des apports croisés des métiers sur la gestion des données de la recherche » : [pdf](/download/R2T2_atelier_donn%C3%A9es_Rivet.pdf), [visio](https://webcast.in2p3.fr/video/un-gt-inter-reseaux-pour-des-apports-croises-des-metiers-sur-la-gestion-des-donnees-de-la-recherche).
 et a ouvert la liste de discussion [donnees-inter-reseaux](/download/Raison_etre_liste_donnees-inter-reseaux.pdf).

En 2020, le groupe a organisé à Grenoble un hackathon intitulé « [Comment améliorer le dépôt et le partage de données de recherche ?](https://gt-donnees2020.sciencesconf.org) » et un webinaire participatif intitulé «Data Paper : une incitation à la qualification et à la réutilisation des jeux de données » : [pgm](Programme_Webinaire_data_paper_5nov2020_GT_Donnees_MITI.pdf), [pdf / visio](datapaper.qmd).

En 2021, deux réseaux ont rejoint le groupe de travail :
[Relier](http://www.relier-univ.fr/), le REseau quaLIté en Enseignement
superieur et Recherche et [RIS](https://ris.cnrs.fr/), le Réseau
Interdisciplinaire autour de la Statistique nous a rejoint. Fin
janvier, le groupe de travail a publié le « [guide de bonnes pratiques
sur les données de la
recherche](https://mi-gt-donnees.pages.math.unistra.fr/guide/)
» qui présente les différentes actions faites par les réseaux autour
de la gestion des données. Ce guide reprend les 7 étapes définies
dans le document « Cartographie des actions des réseaux métiers
autour de la gestion des données » proposé en 2017. Le contenu de
ce guide a été présenté le 3 février lors d\'un
[webinaire](https://www.canal-u.tv/video/atelier_donnees/presentation_du_guide_de_bonnes_pratiques_des_donnees_de_la_recherche.59537).

En juillet, le groupe de travail a réalisé un second webinaire sur le thème de la « [qualité des
données](https://mi-gt-donnees.pages.math.unistra.fr/site/download/2021_07_05_Programme_Webinaire_Qualite.pdf)».

Et en fin d\'année, une « [présentation de la démarche](https://jedata-normande.sciencesconf.org/data/pages/20211203_MC_Quidoz_journee_donnees_normande.pdf)
» qui a donnée naissance au groupe de travail a été faite à la «
journée d\'étude normande sur les données de recherche ».

En mars 2022, le groupe de travail a rendu publique sa «
[charte](/download/charte-gt-donnees_v2.pdf) ».

Le 21 avril 2022 de 14H30 à 17H, le groupe de travail vous invite
au premier webinaire de l\'année. Il sera sur le thème « wikidata
». Pour en savoir plus, cliquer sur ce [lien](wikidata.qmd).
