---
title: "Liste de discussion"
date: 2018-11-27
tags: [liste]
lang: fr
---

Pour faciliter les échanges autour des données de la recherche entre
nos différents réseaux, nous proposons une nouvelle liste de
discussion. Cette liste aura pour objectif de traiter les sujets
portant spécifiquement sur la thématique de gestion et du partage
des données à l'interface des différents métiers et réseaux.

Si les données vous intéressent, inscrivez-vous et participez aux
échanges ! N'hésitez pas à vous inscrire aussi aux listes des réseaux
directement liés à vos activités.

Pour s’inscrire deux méthodes :

- envoyer un message à [sympa@services.cnrs.fr](mailto:sympa@services.cnrs.fr?subject=subscribe donnees-inter-reseaux) avec comme objet 
```
subscribe donnees-inter-reseaux Prénom Nom
```
- se connecter à <https://listes.services.cnrs.fr/wws/info/donnees-inter-reseaux>

Attention seules les demandes faites avec une adresse professionnelle seront acceptées.

Pour accéder aux archives (réservé aux abonnées de la liste), cliquer [ici](https://listes.services.cnrs.fr/wws/arc/donnees-inter-reseaux/)

