---
title: "Qualité des données"
date: 2021-07-5
lang: fr    
format:
  html:
    toc: true
    toc-location: right
    toc-depth: 2
---

## Description

La qualité des données est un thème transversal aux métiers de la
recherche. Cette notion se retrouve sur toutes les étapes du cycle de
vie de la donnée mais elle recouvre des concepts différents (qualité des
données, des métadonnées, du code, de la documentation, de l\'archivage,
\...) mais quelque soit l\'étape, elle peut toujours être vue sous deux
angles : qu\'est ce qu\'une donnée de qualité ? quelle organisation
faut-il mettre en place pour arriver à obtenir des données de qualité ?

## Documents

-   Synthèse du Webinaire (Christine Hadrossek)
    ([pdf](/download/Synthèse_webinaire_qualite.pdf))
-   Programme
    ([pdf](/download/2021_07_05_webinaire_atelier_programme.pdf))
-   Quel lien entre qualité et données ? (Alain Rivet, Cermav et Henri
    Valeins, RMSB)
    ([pdf](/download/2021_07_05_webinaire_atelier_Rivet_Valeins.pdf))
-   Processus de contrôle et qualification des données dans un système
    d'observation océanographique (Christine Coatanoan, Ingénieur
    Gestion de données au Sismer, Ifremer Brest)
    ([pdf](/download/2021_07_05_webinaire_atelier_Coatanoan.pdf))
-   Cycle de vie de la donnée ouverte de qualité (Geoffrey Aldebert,
    Etalab)
    ([pdf](/download/2021_07_05_webinaire_atelier_Aldebert.pdf))
-   Enjeux de la qualité des référentiels et des métadonnées pour la
    communauté scientifique : vocabulaires contrôlés, alignements pour
    une meilleure fairisation et réplicabilité d'un modèle de données -
    au travers de l'exemple des outils de Frantiq. (Blandine Nouvel,
    Centre Camille Jullianet Véronique Humbert, Archéologie des Sociétés
    Méditerranéennes)
    ([pdf](/download/2021_07_05_webinaire_atelier_Humbert_Nouvel.pdf))
-   Retour d'expérience en écologie végétale sur les étapes
    d'homogénéisation des données (Eric Garnier, chercheur CNRS au CEFE)
    ([pdf](/download/2021_07_05_webinaire_atelier_Garnier.pdf))


## Vidéos

- Présentation du GT « Atelier Données » et du webinaire n°2

<iframe width="560" height="315" src="https://www.canal-u.tv/embed/112664?t=0" allowfullscreen></iframe>

- Quel lien entre qualité et données ? (Alain Rivet, Cermav et Henri Valeins, RMSB)

<iframe width="560" height="315" src="https://www.canal-u.tv/embed/112708?t=0" allowfullscreen></iframe>

- Processus de contrôle et qualification des données dans un système d'observation océanographique (Christine Coatanoan, Ingénieur Gestion de données au Sismer, Ifremer Brest)

<iframe width="560" height="315" src="https://www.canal-u.tv/embed/112710?t=0" allowfullscreen></iframe>

- Cycle de vie de la donnée ouverte de qualité (Geoffrey Aldebert, Etalab)

<iframe width="560" height="315" src="https://www.canal-u.tv/embed/112712?t=0" allowfullscreen></iframe>

- Enjeux de la qualité des référentiels et des métadonnées pour la communauté scientifique : vocabulaires contrôlés, alignements pour une meilleure fairisation et réplicabilité d'un modèle de données - au travers de l'exemple des outils de Frantiq. (Blandine Nouvel, Centre Camille Jullianet Véronique Humbert, Archéologie des Sociétés Méditerranéennes)

<iframe width="560" height="315" src="https://www.canal-u.tv/embed/112713?t=0" allowfullscreen></iframe>

- Retour d'expérience en écologie végétale sur les étapes d'homogénéisation des données (Eric Garnier, chercheur CNRS au CEFE)

<iframe width="560" height="315" src="https://www.canal-u.tv/embed/112714?t=0" allowfullscreen></iframe>

