---
title: "Webinaires"
---

# "Datapaper"

5 novembre 2020

Une incitation à la qualification et à la réutilisation des jeux de données

Dans le cadre d’une science ouverte et participative, le data paper permet de rendre plus visible tous les types de données et jeux de
données de recherche dont on peut estimer que le potentiel de réutilisation est important. Il garantit la traçabilité et la qualité de ces données, et précise les modalités d’acquisition ainsi que les conditions et droits d’utilisation.

Néanmoins, pourquoi cette forme éditoriale rencontre-t-elle un tel engouement ? Si certaines communautés produisent depuis plusieurs
années ce type d’article, la libération de la donnée dans le cadre de la science ouverte, son dépôt favorisé ou imposé par les organismes
financeurs en entrepôts institutionnels ouverts, l’application des principes FAIR contribuent fortement à promouvoir le data paper
comme qualifiant incontournable, assurant d’exploiter les «bonnes» données.

Alors, cet élan est-il un reflet fidèle de la réalité, les pratiques de la recherche scientifique sont-elles en train de changer, les
différents acteurs dans la production des données sont-ils plus impliqués dans la transparence et la mise à disposition des données
? Est-ce une opportunité pour les personnels d’accompagnement de la recherche pour valoriser leur rôle ? Et comment rédiger un data
paper, ou le publier ? Comment sont-ils expertisés, sur quels critères ? Le data paper devient-il un enjeu important dans
l’évaluation du producteur de données ?Ce webinaire est ainsi l'occasion de laisser largement la place aux échanges pour tenter
de partager vos points de vue, pour comprendre quelles sont les raisons qui vous amènent à devenir consommateur de data papers.
Comment avez-vous connu ce format éditorial : grâce à votre veille, en découvrant l'existence de data journals ou de rubriques consacrées
au data paper au sein d'une revue académique, parce que tout le monde en parle, en voulant utiliser ou publier des données ?
Qu'avez-vous trouvé dans le data paper qui ne serait pas dans les portails de métadonnées ? Le data paper vous semble-t-il désormais
indispensable et une forme nécessaire de publication accompagnant les données ?. Autant de questions que ce webinaire souhaite aborder
pour évaluer la place que prend le data paper dans l’écosystème de la donnée scientifique.

## Les documents

* [Synthèse du Webinaire du 5 novembre Data Paper par Christine Hadrossek](Christine%20Hadrossek%20-%20Synth%C3%A8se%20webinaire%20du%205%20novembre%20Data%20Paper.pdf)
* [Introduction](Introduction_Stephane_Renault.pdf) : Stéphane Renault
* [Évaluer un data paper : retour d'expérience de la revue Cybergeo](Cybergeo_Denise_Pumain_Clementine_Cottineau_Christine_Kosmopoulos.pdf) : Clémentine Cottineau (CNRS – Centre Maurice Halbwachs), Denise Pumain (Univ. Paris 1 – UMR Géographie-Cités) et Christine Kosmopoulos (CNRS – UMR Géographie-Cités)
* Exemple d’intégration du data paper à un workflow de publication de jeux données : [Sophie Pamerlon (GBIF France – USM Patrimoine naturel)](GBIF_IPT_Sophie_Pamerlon.pdf) et [Annegret Nicolai (Univ.Rennes 1 – UMR ECOBIO, Station Biologique de Paimpont)](BioBlitzSBP_Annegret_Nicolai.pdf)
* Retour d’expérience d’un producteur de data paper : [Victor Gay (Univ. Toulouse 1– École d‘Économie de Toulouse)](REX_TRFGIS_Victor_Gay.pdf)
* Synthèse du webinaire et échanges (à partir des questions du tchat) : [Joachim Schöpfel (Université Lille 3 – GERiiCO)](Synthese_Joachim_Schopfel.pdf)
 
## Les vidéos

### Introduction du Webinaire

<iframe width="560" height="315" src="https://www.canal-u.tv/embed/81841?t=0" allowfullscreen></iframe>

### Évaluer un data paper : retour d\'expérience de la revue Cybergeo

<iframe width="560" height="315" src="https://www.canal-u.tv/embed/81903?t=0" allowfullscreen></iframe>

### Exemple d'intégration du data paper à un workflow de publication de jeux données

<iframe width="560" height="315" src="https://www.canal-u.tv/embed/81901?t=0" allowfullscreen></iframe>

### Retour d'expérience d'un producteur de data paper

<iframe width="560" height="315" src="https://www.canal-u.tv/embed/81905?t=0" allowfullscreen></iframe>

### Synthèse du webinaire et échanges (à partir des questions du tchat)

<iframe width="560" height="315" src="https://www.canal-u.tv/embed/81843?t=0" allowfullscreen></iframe>


# "Qualité des données"

5 juillet 2021

La qualité des données est un thème transversal aux métiers de la
recherche. Cette notion se retrouve sur toutes les étapes du cycle de
vie de la donnée mais elle recouvre des concepts différents (qualité des
données, des métadonnées, du code, de la documentation, de l\'archivage,
\...) mais quelque soit l\'étape, elle peut toujours être vue sous deux
angles : qu\'est ce qu\'une donnée de qualité ? quelle organisation
faut-il mettre en place pour arriver à obtenir des données de qualité ?

## Les documents

-   Synthèse du Webinaire (Christine Hadrossek)
    ([pdf](https://mi-gt-donnees.pages.math.unistra.fr/site/download/Synthèse_webinaire_qualite.pdf))
-   Programme
    ([pdf](https://mi-gt-donnees.pages.math.unistra.fr/site/download/2021_07_05_webinaire_atelier_programme.pdf))
-   Quel lien entre qualité et données ? (Alain Rivet, Cermav et Henri
    Valeins, RMSB)
    ([pdf](https://mi-gt-donnees.pages.math.unistra.fr/site/download/2021_07_05_webinaire_atelier_Rivet_Valeins.pdf))
-   Processus de contrôle et qualification des données dans un système
    d'observation océanographique (Christine Coatanoan, Ingénieur
    Gestion de données au Sismer, Ifremer Brest)
    ([pdf](https://mi-gt-donnees.pages.math.unistra.fr/site/download/2021_07_05_webinaire_atelier_Coatanoan.pdf))
-   Cycle de vie de la donnée ouverte de qualité (Geoffrey Aldebert,
    Etalab)
    ([pdf](https://mi-gt-donnees.pages.math.unistra.fr/site/download/2021_07_05_webinaire_atelier_Aldebert.pdf))
-   Enjeux de la qualité des référentiels et des métadonnées pour la
    communauté scientifique : vocabulaires contrôlés, alignements pour
    une meilleure fairisation et réplicabilité d'un modèle de données -
    au travers de l'exemple des outils de Frantiq. (Blandine Nouvel,
    Centre Camille Jullianet Véronique Humbert, Archéologie des Sociétés
    Méditerranéennes)
    ([pdf](https://mi-gt-donnees.pages.math.unistra.fr/site/download/2021_07_05_webinaire_atelier_Humbert_Nouvel.pdf))
-   Retour d'expérience en écologie végétale sur les étapes
    d'homogénéisation des données (Eric Garnier, chercheur CNRS au CEFE)
    ([pdf](https://mi-gt-donnees.pages.math.unistra.fr/site/download/2021_07_05_webinaire_atelier_Garnier.pdf))


## Les vidéos

### Présentation du GT « Atelier Données » et du webinaire n°2

<iframe width="560" height="315" src="https://www.canal-u.tv/embed/112664?t=0" allowfullscreen></iframe>

### Quel lien entre qualité et données ? (Alain Rivet, Cermav et Henri Valeins, RMSB)

<iframe width="560" height="315" src="https://www.canal-u.tv/embed/112708?t=0" allowfullscreen></iframe>

### Processus de contrôle et qualification des données dans un système d'observation océanographique (Christine Coatanoan, Ingénieur Gestion de données au Sismer, Ifremer Brest)

<iframe width="560" height="315" src="https://www.canal-u.tv/embed/112710?t=0" allowfullscreen></iframe>

### Cycle de vie de la donnée ouverte de qualité (Geoffrey Aldebert, Etalab)

<iframe width="560" height="315" src="https://www.canal-u.tv/embed/112712?t=0" allowfullscreen></iframe>

### Enjeux de la qualité des référentiels et des métadonnées pour la communauté scientifique : vocabulaires contrôlés, alignements pour une meilleure fairisation et réplicabilité d'un modèle de données - au travers de l'exemple des outils de Frantiq. (Blandine Nouvel, Centre Camille Jullianet Véronique Humbert, Archéologie des Sociétés Méditerranéennes)

<iframe width="560" height="315" src="https://www.canal-u.tv/embed/112713?t=0" allowfullscreen></iframe>

### Retour d'expérience en écologie végétale sur les étapes d'homogénéisation des données (Eric Garnier, chercheur CNRS au CEFE)

<iframe width="560" height="315" src="https://www.canal-u.tv/embed/112714?t=0" allowfullscreen></iframe>

# Wébinaire Wikidata{#wikidata}

21 avril 2022

Créée en octobre 2012, Wikidata est une immense base de connaissances
libre éditée par la Wikimedia Foundation, hébergeur de Wikipedia. Éditée
de manière collaborative, elle décrit de manière factuelle une centaine
de millions d'objets de la connaissance humaine dans tous les domaines
(culture générale, géographie, histoire, biologie, linguistique,
physique, etc.).

Les données de Wikidata peuvent être réutilisées librement à travers des
services Web. Le site Histropedia, par exemple, propose la construction
de frises chronologiques à partir des données de Wikidata. Le projet
Open Food Facts exploite les données de Wikidata pour constituer une
base de données libre et ouverte sur les produits alimentaires
commercialisés dans le monde entier.

Les données de Wikidata peuvent aussi servir dans l\'écriture d\'un plan
de gestion de données de type classique ou structuré comme référentiel
de différents éléments (infrastructures, projet de recherche, etc).

Mais Wikidata est également

-   Une communauté structurée par des règles (administrateurs élus par
    la communauté, débat sur l\'ajout de nouvelles propriétés, vie
    privée, etc)
-   Un ensemble d\'outils permettant par exemple l\'importation massive
    et le contrôle qualité des données.
-   Un ensemble de scripts informatiques, effectuant des tâches
    automatiques ou semi-automatiques répétitives.

## Les documents

-   Programme
    ([pdf](https://gt-atelier-donnees.miti.cnrs.fr/download/2022_04_21_webinaire_Wikidata-Programme.pdf))
-   Le Mooc Wikidata (Amélie Charles - Chargée de mission MOOC,
    Wikimedia France)
    ([pdf](https://gt-atelier-donnees.miti.cnrs.fr/download/2022_04_21_webinaire_Wikidata-Charles-MOOC.pdf))
-   Wikidata et la curation des identifiants pérennes des chercheurs
    (Pascal Martinolli - Université de Montréal)
    ([pdf](https://gt-atelier-donnees.miti.cnrs.fr/download/2022_04_21_webinaire_Wikidata-Martinolli-PID.pdf))
-   Gérer, partager et interroger grâce à Wikibase des référentiels
    d\'autorité pour la recherche : l\'exemple de data.biblissima (Régis
    Robineau - Biblissima + Campus Condorcet)
    ([pdf](https://gt-atelier-donnees.miti.cnrs.fr/download/2022_04_21_webinaire_Wikidata-Robineau_Biblissima.pdf))


## Les vidéos

- Wikidata et la curation des identifiants pérennes des chercheurs (Pascal Martinolli - Université de Montréal)

i<iframe width="560" height="315" src="https://www.canal-u.tv/embed/116469?t=0" allowfullscreen></iframe>

- Gérer, partager et interroger grâce à Wikibase des référentiels d\'autorité pour la recherche : l\'exemple de data.biblissima (Régis Robineau - Biblissima + Campus Condorcet)

<iframe width="560" height="315" src="https://www.canal-u.tv/embed/116615?t=0" allowfullscreen></iframe>

- Intégration de Wikibase dans OpenRefine et protocole de réconciliation ((Antonin Delpeuch - OpenRefine / InfAI))

<iframe width="560" height="315" src="https://www.canal-u.tv/embed/116614?t=0" allowfullscreen></iframe>

