---
title: "Wikidata"
date: 2022-04-21
lang: fr    
format:
  html:
    toc: true
    toc-location: right
    toc-depth: 2
---

Créée en octobre 2012, Wikidata est une immense base de connaissances
libre éditée par la Wikimedia Foundation, hébergeur de Wikipedia. Éditée
de manière collaborative, elle décrit de manière factuelle une centaine
de millions d'objets de la connaissance humaine dans tous les domaines
(culture générale, géographie, histoire, biologie, linguistique,
physique, etc.).

Les données de Wikidata peuvent être réutilisées librement à travers des
services Web. Le site Histropedia, par exemple, propose la construction
de frises chronologiques à partir des données de Wikidata. Le projet
Open Food Facts exploite les données de Wikidata pour constituer une
base de données libre et ouverte sur les produits alimentaires
commercialisés dans le monde entier.

Les données de Wikidata peuvent aussi servir dans l\'écriture d\'un plan
de gestion de données de type classique ou structuré comme référentiel
de différents éléments (infrastructures, projet de recherche, etc).

Mais Wikidata est également

- Une communauté structurée par des règles (administrateurs élus par
  la communauté, débat sur l\'ajout de nouvelles propriétés, vie
  privée, etc)
- Un ensemble d\'outils permettant par exemple l\'importation massive
  et le contrôle qualité des données.
- Un ensemble de scripts informatiques, effectuant des tâches
  automatiques ou semi-automatiques répétitives.

## Les documents

-   Programme ([pdf](https://gt-atelier-donnees.miti.cnrs.fr/download/2022_04_21_webinaire_Wikidata-Programme.pdf))
-   Le Mooc Wikidata (Amélie Charles - Chargée de mission MOOC, Wikimedia France)
    ([pdf](https://gt-atelier-donnees.miti.cnrs.fr/download/2022_04_21_webinaire_Wikidata-Charles-MOOC.pdf))
-   Wikidata et la curation des identifiants pérennes des chercheurs
    (Pascal Martinolli - Université de Montréal)
    ([pdf](https://gt-atelier-donnees.miti.cnrs.fr/download/2022_04_21_webinaire_Wikidata-Martinolli-PID.pdf))
-   Gérer, partager et interroger grâce à Wikibase des référentiels
    d\'autorité pour la recherche : l\'exemple de data.biblissima (Régis
    Robineau - Biblissima + Campus Condorcet)
    ([pdf](https://gt-atelier-donnees.miti.cnrs.fr/download/2022_04_21_webinaire_Wikidata-Robineau_Biblissima.pdf))


## Les vidéos

### Wikidata et la curation des identifiants pérennes des chercheurs (Pascal Martinolli - Université de Montréal)

i<iframe width="560" height="315" src="https://www.canal-u.tv/embed/116469?t=0" allowfullscreen></iframe>

### Gérer, partager et interroger grâce à Wikibase des référentiels d\'autorité pour la recherche : l\'exemple de data.biblissima (Régis Robineau - Biblissima + Campus Condorcet)

<iframe width="560" height="315" src="https://www.canal-u.tv/embed/116615?t=0" allowfullscreen></iframe>

### Intégration de Wikibase dans OpenRefine et protocole de réconciliation ((Antonin Delpeuch - OpenRefine / InfAI))

<iframe width="560" height="315" src="https://www.canal-u.tv/embed/116614?t=0" allowfullscreen></iframe>

